var LANGPACK = {
    "en": {
        'Home': 'Home',
        'Contact Info': 'Contact',
        'About Zouzou B&B details': 'Zouzou B&B is located in Tianwei Highway Garden, a.k.a "Home of Flowers", very close to the entrance of Yixinyuan, a place fulfilled with fresh air, beautiful flowers. We truely hope you could enjoy your stay with us.',
        'Contact details': 'Please feel free to contact us if you have any questions.',
        'Room 1': 'On-On',
        'Room 2': 'Umm-Umm',
        'Room 3': 'Gabi',
        'Room 4': 'Na-Na',
        'Room 5': 'Chin-Chin',
        'customer 1 said': 'Vacation at ZouZou: 睡到自然醒的美容覺，一起床就有正妹老闆娘的超豐盛brunch，一起來走走度假吧～',
        'customer 2 said': 'We got a new choice of B&B! Zouzou B&B located in Tienwei Highway Garden, Changhua. The decorating is pretty simple and bright, feel comfortable and like at home. The best part was the homemade breakfast, which made by the hostess! And they also offer free bike to borrow, you can spend a day riding bike around the whole highway garden!',
    },

    "zh_TW": {
        'Copyright': '版權所有',
        'Home': '首頁',
        'About': '關於',
        'Reservation': '訂房',
        'Book Now!': '現在訂房',
        'Blog': '網誌',
        'Contact': '聯絡走走',
        'Contact Us': '聯絡我們',
        'Contact Info': '聯絡資訊',
        'Your Name': '您的姓名',
        'Your Email': '您的電子郵件',
        'Your Phone': '您的聯絡電話',
        'Send Message': '確定送出訊息',
        'Delicious Food': '田園美食',
        'Together': '親友相聚',
        'Moment': '美好時光',
        'Heart': '用心款待',
        'Reasons to choose Zouzou B&B?': '為什麼要選擇走走?',
        'Our Rooms': '精緻房型',
        'as your sweet home': '您旅行的家',
        'Read More': '了解更多',
        'What our customers say?': '聽聽來過走走的他們怎麼說?',
        'No. 173, Section 1, Minzu Rd, Tianwei Township, Changhua County, Taiwan 522': '台灣彰化縣田尾鎮田尾村民族路一段173號',
        'Services': '服務項目',
        'Album': '相簿',
        'About Zouzou B&B': '關於走走',
        'Our Partners': '合作商家',
        'Our Blog': '走走記錄',
        'Your Info': '您的資料',
        'Check-In': '入住日期',
        'Check-Out': '退房日期',
        'Comment': '其他意見',
        'About Zouzou B&B details': '走走位落於彰化田尾公路花園, 近怡心園入口, 我們誠摯地歡迎您, 與我們在這充滿新鮮空氣與花香的好地方悠閒走走。',
        'Breakfast': '美味健康的早餐',
        'Free WiFi': '免費無線網路',
        'No Curfew': '沒有門禁',
        'Sweet Lobby': '溫馨聊天的大廳',
        'and more...': '和更多...',
        'Contact details': '無論是訂房或是景點問題, 都歡迎您利用下方表單與我們進行聯繫。',
        'Food? Sightseeing? What you could have with Zouzou B&B? Click the Read More button to find out more about Zouzou B&B.': '美食? 景點? 在走走您還可以怎麼玩? 請點選下方了解更多按鈕來探索走走。',
        'We have 5 different rooms for you. Reserve your rooms today!': '我們精心設計了 5 間房間, 適合您與家人、朋友相聚出遊, 現在就預訂屬於您的房間!',
        'Check out our latest posts.': '看看最新消息及您我一同在走走留下的足跡',
        'You may find some coupons or special offers with our partners': '入住走走, 您還可以擁有我們合作夥伴所提供的驚喜優惠。',
        'Room 1': '昂昂',
        'Room 2': '恩恩',
        'Room 3': '嘎比',
        'Room 4': '拿拿',
        'Room 5': '欽欽',
        'customer 1 said': '走走度假模式：睡到自然醒的美容覺，一起床就有正妹老闆娘的超豐盛brunch，一起來走走度假吧～',
        'customer 2 said': '喜歡民宿的朋友又多了一個選擇～位在彰化田尾花路公園裡的「走走」招牌是青綠色，屋內風格採清新明亮簡約風，非常自在又舒適，重點是美麗的老闆娘很會做早餐！而且很貼心地提供客人免費租騎腳踏車喲！',

    }
}
